apiVersion: v1
kind: Service
metadata:
  name: kafkatest-svc
  namespace: qa
spec:
  selector:
    app: kafkatest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
